name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --no-cache . --file Dockerfile --tag nginx:from_git
    - name: Push docker image to my repo
      run: echo "samsung@50" | docker login -u prasanthk2002 --password-stdin && docker push nginx:from_git
